set_hitbox_value(AT_EXTRA_1, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 240);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 27);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 21);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_VSPEED, 10);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_MASK,-1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_ANIM_SPEED, 0.2);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_SPRITE, sprite_get("projectile"));
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 9);